---
  - name: Common | Update apt cache
    become: yes
    apt:
      update-cache: yes
      upgrade: safe
      cache_valid_time: 3600

  - name: Common | Install common pkg
    become: yes
    apt: pkg={{ item }} state=installed
    with_items:
      - python3-dev
      - build-essential
      - python-virtualenv
      - python3-pip
      - python3-software-properties
      - libffi-dev
      - libssl-dev
      - libpq-dev
      - git
      - wget
      - gcc 
      - gfortran 
      - g++
      - zsh
      - libhdf5-dev
      - language-pack-en
      - postgresql
      - postgresql-contrib
    tags: common

  - name: Set locale to en_US.UTF-8
    become: yes
    locale_gen: name="en_US.UTF-8" state=present

  - name: "Build hosts file"
    lineinfile:
      dest: /etc/hosts
      regexp: ".*{{ hostvars[item].ansible_hostname }}$"
      line: "{{ hostvars[item].ansible_eth1.ipv4.address }} {{ hostvars[item].ansible_hostname }}"
    with_items: "{{groups['all']}}"
